---
name: FrancescoFerri's Portfolio
markdown: kramdown
include: [_pages, _node_modules]

baseurl: /
url: https://francescoferri.github.io/fcferri.com

collections:
    projects:
        output: true

defaults:
    - scope:
          path: ""
          type: "projects"
      values:
          layout: "project"
